from enum import Enum


class NotificationType(str, Enum):
    MEMBER_ADDED = "MEMBER_ADDED"
    ROLE_CHANGED = "ROLE_CHANGED"

    PROJECT_UPDATED = "PROJECT_UPDATED"

    BOARD_CREATED = "BOARD_CREATED"
    BOARD_UPDATED = "BOARD_UPDATED"
    BOARD_DELETED = "BOARD_DELETED"

    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_COMPLETED = "TASK_COMPLETED"

    TASK_COMMENTED = "TASK_COMMENTED"
    COMMENT_UPDATED = "COMMENT_UPDATED"
    COMMENT_DELETED = "COMMENT_DELETED"

    ATTACHMENT_UPLOADED = "ATTACHMENT_UPLOADED"
    ATTACHMENT_DELETED = "ATTACHMENT_DELETED"

    DEADLINE_APPROACHING = "DEADLINE_APPROACHING"